services:
  - type: web
    name: remote-desktop-app
    env: docker  # Use Docker instead of Python
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: DISPLAY
        value: :99
    healthCheckPath: /health
    plan: starter
