services:
  - type: web
    name: remote-desktop-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
    plan: starter  # or "standard" for better performance
